baseURL = "https://humanitarian-user-group.github.io"
languageCode = "en"
title = "HumanitaRian useR group"
theme = "hugo-future-imperfect"
enableRobotsTXT = true
PygmentsCodeFences = true
canonifyurls = true

# Disqus Username
disqusShortname = "https-humanitarian-user-group-github-io"

# Google Analytics UA number
googleAnalytics = "UA-131350181-1"

# Copyright of your post
copyright = "© This post is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License，please give source if you wish to quote or reproduce."

# Initial site menu, you can extend menu with content.
[[menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"


[[menu.main]]
  name = "Tags"
  weight = 20
  identifier = "tags"
  url = "/tags/"

[[menu.main]]
  name = "Categories"
  weight = 30
  identifier = "categories"
  url = "/categories/"

[[menu.main]]
  name = "Join the Skype-group"
  pre = "<i class='fa fa-phone fa-fw'></i>"
  weight = 40
  url = "https://join.skype.com/qYBKC5q3wKp4"

# Add your own params here
[params]
  author = "HumanitaRian-useR-group"
  bg = "images/grey-prism.svg"
  avatar = "images/avatar.png"
  favicon = "images/favicon.ico"
  favicon16 = "images/favicon-16x16.png"
  favicon32 = "images/favicon-32x32.png"
  iconWindows = "images/tile-image-windows.png"
  iconApple = "images/touch-icon-apple.png"
  iconAndroid = "images/touch-icon-android.png"
  seotitle = "HumanitaRian-useR-group"
  subtitle = "~ Science is show me - not trust me ~"
  description = "The humanitarian data analysis professional community shall work towards using a common and open language to build interoperable and transparent analysis standards for joint needs assessments and to obtain maximum value for any data collected."
  paginate = 10

  ## Add highlight
  disable_highlight = false
  highlightjsVersion = "9.11.0"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml"]
  highlightjsTheme = "github"


  # Choose your social networks
  email = "humanitarian.user@gmail.com"
  github = "HumanitaRian-useR-group"
  twitter = "HumanitaRianus1"
  linkedin = "https://www.linkedin.com/groups/8732707/"


